version: '3.4'
services:
  api:
    container_name: api
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: dev # or prod for production
    environment:
      - POSTGRES_HOST=db # name of the "db" service
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=need-to-replace
    volumes:
      - ./../:/usr/src/app
    ports:
      - "9091:9000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:15.2-alpine3.17
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./../database/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=need-to-replace
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
